### ISSUE TITLE
Comparing memory diagram to Java Visualizer

### ISSUE THREAD

**Issue by hcientist** [ChrisMayfield/cspogil#26]
Java Visualizer for the `TaylorSwift.java` in CS Act03 seems to (no longer?) show Strings as references, but they look more similar to primitives. Possibly this is a reason to use a different visualizer or else to have the facilitator call out the format that works best for them? Maybe this was an intentional choice because of some of Java's handling `String`s and their literals a little different than instances of other classes?

**Comment by ChrisMayfield** [comment]
The default setting of Java Visualizer (both on Waterloo's server and on Python Tutor) is for "Show String/Integer/etc objects, not just values" to be unchecked. However, the links I embedded in the activity and on my website turn that option on. I'll add to the facilitation notes that instructors should make sure that option is enabled so that students will see the references drawn as arrows.

**Comment by hcientist** [comment]
Hey thanks for the quick follow up @ChrisMayfield . I was just coming back to post. I found that option, but I'm disappointed not have have found a way yet that successfully preserves it. [The link in the activity](https://github.com/ChrisMayfield/cspogil/blob/cd4ea674a1b5f46a2c86de0e6307c60151ff7e8c/CS1/Act03/reference-types.tex#L125) does not work as I think either of us would expect in Firefox nor Chrome (didn't try elsewhere)

**Comment by hcientist** [comment]
🤦‍♂️ Looks like it may actually work as you expect and not as I expect  😂 I thought the intention was for the link to have the `TaylorSwift` class already in the editor, but it looks like the goal was instead to give them the blank slate, with the exception of the option being ticked. That seems to work.

**Comment by ChrisMayfield** [comment]
That's a good idea, though -- to embed the TaylorSwift code into the link.
